raspberrypi/rpi-eeprom

rpi-eeprom-update

More the checkDependencies call to after the options parsing so that
-h can be run for help2man.

rpi-eeprom-update: -h should not require vcgencmd

---

rpi-eeprom-update

Also ensure 0 as default bootloader timestamp for both JSON and non-JSON.

Restore machine output exit code as string

---

rpi-eeprom-update

Running 'sudo rpi-eeprom-update' will remove update files from the
boot partition. Since the user may run this command to check if
an update is required it will have the surprising side effect of
removing the pending update applied by the systemd service which
runs 'rpi-eeprom-update -a' at startup.
Move the cleanup code so that it only runs if a manual or automatic
update was requested.
Add an explicit option (-r) to just remove the previous update files.

rpi-eeprom-update: Don't remove update files if run with no arguments

---

rpi-eeprom-update

If the rpi-eeprom-images checksums file is available then validate
the checksums before applying the update.
Add a -i option to ignore checksums, this should only be required for
developers or people who have cloned the rpi-eeprom Github and installed
new files which are not available in the apt package.

rpi-eeprom-update: Verify DPKG checksums if available

---

rpi-eeprom-update

Make up-to-date message specific to bootloader or vl805 and indicate if
the tool was not run as root.

Tweak update status for BOOTLOADER, VL805

---

rpi-eeprom-config

This PR is maybe not the best ("most Pythonic") fix, but it works...
With Python3, the following errors occur:
```
rpi4:~/zz1 # rpi-eeprom-config --config old.config /usr/lib/kernel-overlays/base/lib/firmware/raspberrypi/bootloader/critical/pieeprom-2019-09-10.bin >new.bin
Traceback (most recent call last):
File "/usr/bin/rpi-eeprom-config", line 107, in <module>
main()
File "/usr/bin/rpi-eeprom-config", line 102, in main
image.write(args.config)
File "/usr/bin/rpi-eeprom-config", line 81, in write
sys.stdout.write(self._bytes)
TypeError: write() argument must be str, not bytearray
```
and
```
rpi4:~/zz1 # rpi-eeprom-config /usr/lib/kernel-overlays/base/lib/firmware/raspberrypi/bootloader/critical/pieeprom-2019-09-10.bin  >new.config
Traceback (most recent call last):
File …
```

Add Python3 support

---

rpi-eeprom-update

`vl805` is really quite slow for some reason - when called it quickly outputs the version number, then there's about a 1 second delay for no apparent reason.
`rpi-eeprom-update` calls `vl805` twice to `grep` the version number incurring this delay two times. This change avoids the second unnecessary call on systems without `lspci`.
`lspci` is also much quicker, and will now be used instead of `vl805` when it is available (ref: https://github.com/raspberrypi/rpi-eeprom/issues/48#issuecomment-550527518).
```
rpi4:~ # time /usr/bin/rpi-eeprom-update
BOOTLOADER: up-to-date
CURRENT: Tue Sep 10 10:41:50 UTC 2019 (1568112110)
LATEST: Tue Sep 10 10:41:50 UTC 2019 (1568112110)
VL805: up-to-date
CURRENT: 000137ab
LATEST: 000137ab
real    0m 2.05s
user    0m 0.09s
sys     0m 1.94s
```
``` …
```

use lspci if available instead of vl805. Avoid calling vl805 twice.

---

rpi-eeprom-config

The current help text for rpi-eeprom-config is unclear. This PR changes them so that the help text matches what the tool does and what each parameter specifies. The man page, automatically derived from the help text, is also fixed.

rpi-eeprom-config - fix up help text (and therefore also man page)

---

rpi-eeprom-update

Deprecate the vl805.latest file and compare version numbers. This
ensures that the rpi-eeprom-update will never downgrade the VL805.

rpi-eeprom-update: Improve version selection for VL805

---

rpi-eeprom-update

Add the option for board-revision specific bootloaders firmware. This
allows critical firmware updates to be applied to specific board
revisions first before these are promoted to the generic firmware
directories.
Update the find operation to follow symlinks so that EEPROM images
in the board revision specific subdirectories can be links to the
generic images.

rpi-eeprom-update: Add support for board-revision specific images.

---

firmware/raspberry_pi4_network_boot_beta.md

Added extra clarification for the beta `.bin` file, removing the static date from the command, as plenty of people would definitely copy/paste that blindly without realizing there are multiple versions in that directory. (Me being one of those people)

Clarifying the Dated .bin files

---

rpi-eeprom-update

The vl805 utility is not available for aarch64 and is deprecated
because it's only required for USE_FLASHROM.
Remove the dependency check so that it can be removed from the package.
The USE_FLASHROM code will be removed at a later date once the
self-update mechanism in the bootloader EEPROM is released.

rpi-eeprom-update: Remove dependency on vl805

---

rpi-eeprom-update

This patch allows `rpi-eeprom-update` to fall back to the firmware/ directory in the same directory as `rpi-eeprom-update`, if all else fails.  Good for running directly from the git checkout, as the repo doesn't have an install target by itself and mostly assumes being part of a .deb.

Allow for run from local git checkout

---

rpi-eeprom-config

There's a CM4 on the way at some point in the future, so change reference in usage text to Pi 4B to Pi 4 instead. (Assumes CM4 has a bootloader EEPROM chip).

rpi-eeprom-config: Pi 4B -> Pi 4

---

rpi-eeprom-update

This would allow, for example a GUI, to hide/disable (or perhaps make read only) the VL805 update option when the VL805 eeprom is not present.

include vl805 eeprom presence in machine output

---

rpi-eeprom-update

The -d option has two meanings - it will, as described, insert the default configuration into the new EEPROM image if no file is specified. But it also has the as-yet-undocumented meaning of using the configuration contained in any file specified using the -f flag, rather than migrating the current config. This PR documents this second meaning.

rpi-eeprom-update - fix description of -d flag

---

rpi-eeprom-update

Use `-lt` rather than `\<` so that, for example, this:
[ 2 -lt 17 ]
is true (whereas with `\<` in place of `-lt` it's false).
Signed-off-by: Kyle J. McKay <mackyle@gmail.com>

rpi-eeprom-update: compare versions algebraically

---

rpi-eeprom-update

I've been putting together an Ubuntu package for rpi-eeprom and noticed in rpi-eeprom-update that it queries the now deprecated rpi-eeprom-images package, instead of rpi-eeprom. I'm assuming this needs correcting now that rpi-eeprom-images is effectively empty?

Query checksums from rpi-eeprom instead of rpi-eeprom-images

---

rpi-eeprom-config

This change makes it work (at least) with NixOS out-of-the box, given that Python is installed in the environment.

Use /usr/bin/env python to make rpi-eeprom-config more portable

---

rpi-eeprom-update

Upstream kernels do not list the board revision in /proc/cpuinfo. Get it
from the device tree instead.

rpi-eeprom-update: Upstream kernel fix

---

rpi-eeprom-update

Bug fix for Raspberry Pis with low BOARD_INFO numbers. Tell hexdump to display all input data with `-v` so that zeros don't get mangled.

Fix #211 - hexdump error on older Pi models

---

rpi-eeprom-update

```
This command pipeline:
printf '00000000000000000000000000000000' | od -An -t x1 | tr -d ' '
produces this output:
30303030303030303030303030303030
*
Add a `-v` to od and a `\n` to the tr arg like so:
printf '00000000000000000000000000000000' | od -v -An -t x1 | tr -d ' \n'
to instead produce this output:
3030303030303030303030303030303030303030303030303030303030303030
Although it's unlikely that the revision value would generate multiple
lines or contain duplicate lines, it's better to be safe than sorry
especially since the changes to do so do not introduce any extra overhead
and use only POSIX-specified options/arguments.
It's also possible this code fragment could be copied and pasted elsewhere
to provide a "hexdump" of something that might be expected to generate
multiple lines …
```

rpi-eeprom-update: avoid any possible od accidents

---

debian/control

Canonical have discovered an issue with the rpi-eeprom package: the package architecture is set to `all` - it should be `armhf arm64` - see https://bugs.launchpad.net/ubuntu/+bug/1884748. This PR corrects the issue here, in the upstream repo.
Rationale: the package will only work on a Raspberry Pi 4, so suggesting it works on architectures the Pi 4 doesn't use is misleading.
N.B. I have no association with Canonical - I just spotted it on their bug tracker.

Fix package architecture

---

rpi-eeprom-config
rpi-eeprom-update

* Add a simple 'git commit' inspired --edit option which retrieves the current config, spawns default editor then merges the new config into the latest release and schedules the update.
* Add  "--apply" flag which is a non-interactive version of the above where the new config file is specified on the command line instead of spawning and editor
@jdb @pelwell Here's the 'porcelain' additions which I was talking about earlier, no rush to merge but if you could update and add feedback when you get chance that would be great. Hopefully, the error handling is now improved.
git clone -b rpi_eeprom_config_apply https://github.com/timg236/rpi-eeprom.git
sudo ./rpi-eeprom/test/install

Update rpi-eeprom-config to provide wrap simple interactive and non-interactive update opertions

---

rpi-eeprom-config
rpi-eeprom-update

Add the timestamp to pieeprom.sig for use with a future bootloader
update.
This is not relevant for the VL805 firmware because it is not
configurable.

Add the timestamp of the update to the pieeprom.sig file.

---

rpi-eeprom-config

Always use the current EEPROM configuration unless there is an
update pending in which case use that to support incremental edits.
Update help and update message to indicate that
'sudo rpi-eeprom-update -r'
may be used to cancel a pending update.
Fix a few comments

rpi-eeprom-config: Change --edit to use the current EEPROM config

---

rpi-eeprom-config
rpi-eeprom-update

Firmware files enabling the blconfig device aren't available yet, so I can't fully test this. That said I think the code is ready for a first review.

rpi-eeprom-update: Get bootloader configuration from DT

---

rpi-eeprom-config

The previous implementation was reading the sysfs files as plain text
and encoding them as 'ascii' to remove all the trailing zeros. This is
wrong twofold. To start with, the sysfs file we're querying are binary
files[1], and we're reading it as a string. On top of that we're
benefiting that *some* python implementations of string.encode() will
deal with trailing zeros.
Fix this by marking the files as binary and decoding them as strings
before consuming them.
[1] sysfs files are generally text based, but there is also the option
to output binary data. Our configuration file does the later.

rpi-eeprom-config: Properly decode sysfs binary files

---

rpi-eeprom-update

Update the human readable version of the version information to indicate
that raspi-config may be used to change the release type.
raspi-config can be replaced with other program names if necessary.

rpi-eeprom-update: Reference raspi-config from version message

---

rpi-eeprom-config
rpi-eeprom-update

Some users might forcibly install this on a board that isn't an rpi4.
Exit early, and explain why the program can't be run.

rpi-eeprom-config/update: Exit cleanly when not run on rpi4

---

rpi-eeprom-update

The muxing of the SPI EEPROM and analog audio pins makes flashrom
usage unreliable and having two flashing mechanisms adds unnecessary
complexity to this script.
The bootloader supports EEPROM updates from USB-MSD, Network
and rpiboot there is no real need to support flashrom within this
utility. Therefore, the option to use flashrom can be removed from this
script.

rpi-eeprom-update: Remove deprecated flashrom script options.

---

rpi-eeprom-update

The 'strings' utility is installed by binutils whereas 'tr' belongs with
coreutils. Minimal systems will only contain the latter, due to binutils'
size (20-50 MB). So, convert all uses of 'strings' to 'tr' so as to
avoid the package dependency.
The second 'tr' usage converts non-ASCII characters into newlines so as
to isolate the "BUILD_TIMESTAMP=1234567890" statement (similar to what
'strings' does). There is no need for this in the first one: non-ASCII
characters are simply discarded as DT aliases have a fixed one line
format.

rpi-eeprom-update: Use 'tr' instead of 'strings'

---

rpi-eeprom-update

It seems that [:print:] could be substituted by rogue shells[1], so
surround it with quotes to make sure it doesn't happen. Use single
quotes as they are the most constraining kind. All in all, this change
should be harmless.
[1] https://github.com/raspberrypi/rpi-eeprom/pull/298#issuecomment-784542905

rpi-eeprom-update: Surround [:print:] with quotes

---

imager/make-beta-release

Builds `beta_release/*.zip` from the latest files found in `firmware/beta/`

Add make-beta-release as a wrapper around make-release

---

rpi-eeprom-update

For the default bootloader release skip automatic updates unless the bootloader is older than a specified minimum version.

rpi-eeprom-update: Set a minimum version number for silent updates

---

rpi-eeprom-update

This is only meant to be hyphenated when used as a compound adjective, which is not the case here. See https://www.thewriter.co.uk/tools/style-guide/punctuation/hyphens#:~:text=When%20it%20comes%20after%20the,up%2Dto%2Ddate%20document.

rpi-eeprom-update: up-to-date -> up to date

---

rpi-eeprom-update

At present, the update script exits cleanly in the case it finds itself run on Pi hardware prior to the 4/CM4/400, but if installed on non-Pi hardware exits with various slightly cryptic errors (missing `vcgencmd` and some subsequent math errors from trying to bit-shift the empty `BOARD_INFO` variable).
This patch adds a similar exit to the non-Pi 4 case, with a slightly more useful message. It may seem rather academic but as rpi-eeprom is now in the Ubuntu armhf and arm64 archives it can theoretically (although not sensibly :) be installed on something like an AWS arm64 container.
It's arguable whether it should be a "clean" exit in this scenario. However, consider the example of a non-Pi system which has a "Revision" entry in `/proc/cpuinfo` (although obviously not a Pi revision). In …

Add a test to cause the script to exit cleanly on non-Pi hardware

---

imager/make-release

Previously, the .sig would have an update timestamp of zero. Switching
to rpi-eeprom-digest is preferable because the update timestamp will
be much closer to when the image was installed.
N.B. Update-timestamp is used to track configuration changes and is
independent of the build-timestamps which are the version of the
bootloader executable.

make-release: Use rpi-eeprom-digest to generate update timestamps

---

rpi-eeprom-update

Self-update is preferred to using recovery.bin because it avoids modifiy the
boot partition in order to rename recovery.bin after use. Since the 2711 ROM
does not support network or USB MSD loading of recovery.bin self-update has to
be used with other boot modes anyway.
If RPI_EEPROM_SELF_UPDATE=1 then avoid installing recovery.bin so long as the
current bootloader version supports self-update from SD/MMC and that doesn't
look as though SELF_UPDATE has been disable in the EEPROM config.
RPI_EEPROM_SELF_UPDATE is currently set to 0 by default because this is is an experimental change.

rpi-eeprom-update: Avoid using recovery.bin if the current bootloader supports self-update

---

rpi-eeprom-update

Whilst working on adding support for rpi-eeprom to the meta-raspberrypi yocto layer (see https://github.com/agherzan/meta-raspberrypi/pull/1131) I found that the following logic in rpi-eeprom-update to find the nvmem path in sysfs was broken when run using busybox find.
```
local blconfig_alias="/sys/firmware/devicetree/base/aliases/blconfig"
local blconfig_nvmem_path=""
if [ -f "${blconfig_alias}" ]; then
local blconfig_ofnode_path="/sys/firmware/devicetree/base"$(strings "${blconfig_alias}")""
local blconfig_ofnode_link=$(find -L /sys/bus/nvmem -samefile "${blconfig_ofnode_path}" 2>/dev/null)
if [ -e "${blconfig_ofnode_link}" ]; then
blconfig_nvmem_path=$(dirname "${blconfig_ofnode_link}")
fi
fi
```
gnu find 4.8.0 (from raspbian)
```
pi@raspberrypi:~$ find -L /sys/bus/nvmem/devices/ …
```

Fix rpi-eeprom-update when using busybox find

---

rpi-eeprom-update

latest and default are links to directories, so follow them.
Before:
/usr/bin/rpi-eeprom-update
BOOTLOADER: up to date
CURRENT: Wed Jan 11 17:40:52 UTC 2023 (1673458852)
LATEST: Thu Jan  1 00:00:00 UTC 1970 (0)
RELEASE: critical (/lib/firmware/raspberrypi/bootloader/critical)
After:
/usr/bin/rpi-eeprom-update
BOOTLOADER: up to date
CURRENT: Wed Jan 11 17:40:52 UTC 2023 (1673458852)
LATEST: Wed Jan 11 17:40:52 UTC 2023 (1673458852)
RELEASE: critical (/lib/firmware/raspberrypi/bootloader/critical)
Signed-off-by: Ivan T. Ivanov <iivanov@suse.de>

rpi-eeprom-update: Follow links when looking for latest EEPROM

---

rpi-eeprom-update

Looks like some things have moved around in Bookworm.
Inspired by #510 :wink:

rpi-eeprom-update: Fix package-names in error messages

---

rpi-eeprom-update

Use flashrom by default on Pi5 unless the the RPI_EEPROM_USE_FLASHROM environment variable has been set to zero OR flashrom is not available.

rpi-eeprom-update: Use flashrom by default on Pi5

---

rpi-eeprom-update

Output non-fatal warnings to stderr in order to avoid breaking programs like rpi-eeeprom-config which parse the output of rpi-eeprom-update.
Fixes: https://github.com/raspberrypi/rpi-eeprom/issues/548

rpi-eeprom-update: Output warnings to stderr

---

rpi-eeprom-config

Allows you to add a custom ca cert to an image. Needs an update to the image format to add a space for the new file

Add new cacertder option

---

rpi-eeprom-config
rpi-eeprom-digest
tools/rpi-sign-bootcode

* Improve help documentation for rpi-eeprom-digest to make it clearer that this is a low level tool for signing binary files and that the wrapper script must be used for creating a secure-boot SPI flash image.
* Add the 2712 code signing tools to support secure-boot firmware (once released)

Secure boot tools

---

rpi-eeprom-config

Update to allow all file replacement arguments to be passed in a single call.
Also, add debug flags and update the instructions for installing pycryptodome

rpi-eeprom-config - Fix handling of bootcode arg

---

firmware-2712/release-notes.md

- 2024-07-30 is marked `default` here, but the image is actually in the `latest` directory - fix that
- 2024-07-25 doesn't specify default or latest - fix that
(Aside: neither seem to have found their way to apt yet).

BCM2712 release-notes.md - correct notes for most recent 2 releases

---

rpi-eeprom-config

20 seconds is a little too short for safety with flashrom if every page has to be erased and re-written. Bump this to 60 seconds which is probably too long but nothing good will come from interrupting flashrom.

rpi-eeprom-config: Increase the timeout for flashrom shell-cmd

---

rpi-eeprom-digest

If used in a build environment that sets SOURCE_DATE_EPOCH, we should honour that in order to generate reproducible binaries.
See https://reproducible-builds.org/specs/source-date-epoch/ .

rpi-eeprom-digest: honour SOURCE_DATE_EPOCH

---

firmware-2712/release-notes.md

While trying out this new feature, I discovered that I needed to specify WAIT_FOR_POWER_BUTTON=1, rather than ...BTN=1 for it to work. (Found by running `strings` on the image).

2712 release-notes.md: correct name of new config parameter
